<a href="https://colab.research.google.com/github/2303A52060/AI_machine_learning_coders/blob/main/ML_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#USING PUBLIC DATABASES WITH TENSORFLOW DATASETS
#GETTING STARTED WITH TFDS
!pip install tensorflow-datasets
import tensorflow as tf
import tensorflow_datasets as tfds
mnist_data=tfds.load('fashion_mnist')
for item in mnist_data:
  print(item)
mnist_train=tfds.load(name='fashion_mnist',split='train')
assert isinstance(mnist_train,tf.data.Dataset)
print(type(mnist_train))
for item in mnist_train.take(1):
  print(type(item))
  print(item.keys())
for item in mnist_train.take(1):
  print(type(item))
  print(item.keys())
  print(item['image'])
  print(item)

train
test
<class 'tensorflow.python.data.ops.prefetch_op._PrefetchDataset'>
<class 'dict'>
dict_keys(['image', 'label'])
<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]


In [2]:
mnist_test,info=tfds.load(name='fashion_mnist',with_info='True')
print(info)

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_dir='/root/tensorflow_datasets/fashion_mnist/3.0.1',
    file_format=tfrecord,
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=uint8),
        'label': ClassLabel(shape=(), dtype=int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    nondeterministic_order=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr

In [3]:
mnist=tf.keras.datasets.fashion_mnist
(training_images,training_labels), (test_images,test_labels)=mnist.load_data()

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [4]:
(training_images,training_labels),
(test_images,test_labels)=tfds.as_numpy(tfds.load(name="rock_paper_scissors",split=["train","test"],as_supervised=True))

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/rock_paper_scissors/incomplete.J8HTMV_3.0.0/rock_paper_scissors-train.tfre…

Generating test examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/rock_paper_scissors/incomplete.J8HTMV_3.0.0/rock_paper_scissors-test.tfrec…

Dataset rock_paper_scissors downloaded and prepared to /root/tensorflow_datasets/rock_paper_scissors/3.0.0. Subsequent calls will reuse this data.


In [5]:
import tensorflow as tf
import tensorflow_datasets as tfds
(training_images, training_labels), (test_images, test_labels) = tfds.as_numpy(tfds.load(
    'fashion_mnist',
    split=['train', 'test'],
    batch_size=-1,
    as_supervised=True
))
training_images=training_images/255.0
test_images=test_images/255.0
model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28,1)),
    tf.keras.layers.Dense(512,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10,activation='softmax')
])
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(training_images,training_labels,epochs=5)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8222 - loss: 0.4976
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 2ms/step - accuracy: 0.8607 - loss: 0.3811
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8702 - loss: 0.3500
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8794 - loss: 0.3282
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8852 - loss: 0.3099


In [6]:
#keras_models_2
import tensorflow as tf
import tensorflow_datasets as tfds

data=tfds.load('horses_or_humans',split='train',as_supervised=True)
train_batches=data.shuffle(100).batch(10)
model=tf.keras.Sequential([
    tf.keras.layers.Conv2D(16,(3,3),activation='relu',input_shape=(300,300,3)),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(32,(3,3),activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64,(3,3),activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64,(3,3),activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64,(3,3),activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512,activation='relu'),
    tf.keras.layers.Dense(1,activation='sigmoid')
])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
history=model.fit(train_batches,epochs=10)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/horses_or_humans/incomplete.VGFAZE_3.0.0/horses_or_humans-train.tfrecord*.…

Generating test examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/horses_or_humans/incomplete.VGFAZE_3.0.0/horses_or_humans-test.tfrecord*..…

Dataset horses_or_humans downloaded and prepared to /root/tensorflow_datasets/horses_or_humans/3.0.0. Subsequent calls will reuse this data.
Epoch 1/10


/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


103/103 ━━━━━━━━━━━━━━━━━━━━ 17s 79ms/step - accuracy: 0.8880 - loss: 1.7400
Epoch 2/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.9815 - loss: 0.0654
Epoch 3/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.9834 - loss: 0.0404
Epoch 4/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.9961 - loss: 0.0141
Epoch 5/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.9747 - loss: 0.0808
Epoch 6/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.9679 - loss: 0.1028
Epoch 7/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 1.0000 - loss: 0.0013
Epoch 8/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 1.0000 - loss: 1.9973e-04
Epoch 9/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 1.0000 - loss: 9.5212e-05
Epoch 10/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 1.0000 - loss: 5.6304e-05


In [1]:
1.#USING TDFS WITH KERAS MODELS
# Import TensorFlow and TensorFlow Datasets
import tensorflow as tf
import tensorflow_datasets as tfds

# Load the Fashion-MNIST dataset (train and test sets)
# tfds.load returns TensorFlow dataset objects, we convert them to NumPy arrays
(training_images, training_labels), (test_images, test_labels) = tfds.as_numpy(
    tfds.load('fashion_mnist',
              split=['train', 'test'],   # split into training and testing sets
              batch_size=-1,             # load all data in one batch
              as_supervised=True)        # return (image, label) pairs
)

# Normalize pixel values (0–255 → 0–1) for better training performance
training_images = training_images / 255.0
test_images = test_images / 255.0

# Build a Sequential neural network model
model = tf.keras.models.Sequential([
    # Flatten layer: converts 28x28 image into a 784-element vector
    tf.keras.layers.Flatten(input_shape=(28,28,1)),

    # Hidden Dense layer: 128 neurons, ReLU activation for non-linearity
    tf.keras.layers.Dense(128, activation=tf.nn.relu),

    # Dropout layer: randomly drops 20% of neurons during training to prevent overfitting
    tf.keras.layers.Dropout(0.2),

    # Output Dense layer: 10 neurons (one per class), softmax activation for probability distribution
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

# Compile the model: define optimizer, loss function, and evaluation metric
model.compile(
    optimizer='adam',                          # Adam optimizer (adaptive learning rate)
    loss='sparse_categorical_crossentropy',    # suitable for integer labels (0–9)
    metrics=['accuracy']                       # track accuracy during training/testing
)

# Train the model on training data for 5 epochs (5 passes through the dataset)
model.fit(training_images, training_labels, epochs=5)


Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/fashion_mnist/incomplete.4CD5CY_3.0.1/fashion_mnist-train.tfrecord*...:   …

Generating test examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/fashion_mnist/incomplete.4CD5CY_3.0.1/fashion_mnist-test.tfrecord*...:   0…

Dataset fashion_mnist downloaded and prepared to /root/tensorflow_datasets/fashion_mnist/3.0.1. Subsequent calls will reuse this data.


/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8134 - loss: 0.5303
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8545 - loss: 0.3991
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8668 - loss: 0.3653
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8740 - loss: 0.3461
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8778 - loss: 0.3313


In [2]:
2.#USING TDFS WITH KERAS MODELS
import tensorflow as tf
import tensorflow_datasets as tfds

# Load dataset (horses vs humans)
data = tfds.load('horses_or_humans', split='train', as_supervised=True)
train_batches = data.shuffle(100).batch(10)  # shuffle + batch

# Build CNN model
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16, (3,3), activation='relu', input_shape=(300,300,3)), # feature detection
    tf.keras.layers.MaxPooling2D(2,2),  # reduce size

    tf.keras.layers.Conv2D(32, (3,3), activation='relu'), # deeper features
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(64, (3,3), activation='relu'), # even deeper features
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Flatten(),  # convert to 1D
    tf.keras.layers.Dense(512, activation='relu'),  # fully connected layer
    tf.keras.layers.Dense(1, activation='sigmoid')  # output: horse or human
])

# Compile model (optimizer + loss + metric)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train model
history = model.fit(train_batches, epochs=10)


Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/horses_or_humans/incomplete.DLH1UT_3.0.0/horses_or_humans-train.tfrecord*.…

Generating test examples...: 0 examples [00:00, ? examples/s]

Shuffling /root/tensorflow_datasets/horses_or_humans/incomplete.DLH1UT_3.0.0/horses_or_humans-test.tfrecord*..…

Dataset horses_or_humans downloaded and prepared to /root/tensorflow_datasets/horses_or_humans/3.0.0. Subsequent calls will reuse this data.
Epoch 1/10


/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


103/103 ━━━━━━━━━━━━━━━━━━━━ 14s 67ms/step - accuracy: 0.8578 - loss: 58.4757
Epoch 2/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.9903 - loss: 0.0414
Epoch 3/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 1.0000 - loss: 9.8958e-04
Epoch 4/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 1.0000 - loss: 1.4962e-04
Epoch 5/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 1.0000 - loss: 6.0221e-05
Epoch 6/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 1.0000 - loss: 3.4069e-05
Epoch 7/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 1.0000 - loss: 1.9072e-05
Epoch 8/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 1.0000 - loss: 1.1632e-05
Epoch 9/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 1.0000 - loss: 7.3575e-06
Epoch 10/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 1.0000 - loss: 5.3606e-06


In [5]:
#Using Mapping Functions for Augmentation
# Import necessary libraries
import tensorflow as tf
import tensorflow_datasets as tfds

# -------------------------------
# 1. Load the dataset
# -------------------------------
# 'horses_or_humans' is a binary classification dataset
# as_supervised=True ensures we get (image, label) pairs
data = tfds.load('horses_or_humans', split='train', as_supervised=True)

# -------------------------------
# 2. Define augmentation function
# -------------------------------
def augment_images(image, label):
    # Convert image to float32 for processing
    image = tf.cast(image, tf.float32)

    # Normalize pixel values to range [0,1]
    image = image / 255.0

    # Apply random horizontal flip
    image = tf.image.random_flip_left_right(image)

    # Apply random brightness adjustment
    image = tf.image.random_brightness(image, max_delta=0.1)

    # Apply random contrast adjustment
    image = tf.image.random_contrast(image, lower=0.9, upper=1.1)

    return image, label

# -------------------------------
# 3. Apply augmentation using map()
# -------------------------------
# The map() function applies augment_images to each (image, label) pair
train = data.map(augment_images)

# -------------------------------
# 4. Shuffle and batch the dataset
# -------------------------------
# Shuffle with buffer size 100, then batch into groups of 32
train_batches = train.shuffle(100).batch(32)

# -------------------------------
# 5. Build a simple CNN model
# -------------------------------
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(300,300,3)),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax)  # 2 classes: horse or human
])

# -------------------------------
# 6. Compile the model
# -------------------------------
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# -------------------------------
# 7. Train the model
# -------------------------------
# Train for a few epochs using augmented batches
history = model.fit(train_batches, epochs=5)

# -------------------------------
# 8. Evaluate (optional)
# -------------------------------
# You can load the test split and evaluate similarly
test_data = tfds.load('horses_or_humans', split='test', as_supervised=True)
test = test_data.map(augment_images).batch(32)
model.evaluate(test)


SyntaxError: unterminated string literal (detected at line 58) (1494263878.py, line 58)